### ISSUE TITLE
sample usage?

### ISSUE THREAD

**Issue by hannesm** [cryptosense/pkcs11#34]
Hello,

I don't know much about smartcards etc.  My question is: can I use this library (and if so, how) to interact with a PKCS11 smartcard (in my case likely a yubikey (I got some yubikey hardware recently), there seems to be https://developers.yubico.com/yubico-piv-tool/YKCS11_release_notes.html).

Is there by any chance a sample application (whatever, a command-line utility to sign a blob using the key in the smartcard) for this library available?

thanks,

hannes

**Comment by gram** [comment]
Hi Hannes, 

Yubikey PKCS11 - yes should work
Sample application - hmm good idea we can probably add something. I'll talk to the team when I get back to France next week.

**Comment by hannesm** [comment]
@gram thx!

**Comment by emillon** [comment]
Hello @hannesm,

This looks like a good idea indeed, especially since the API is a bit large.

I can add a sample application that given a DLL, slot number, PIN, key label and plaintext file in `argv`, computes and displays a RSA PSS signature (the key pair can be generated by other means, for example `pkcs11-tool`).

In the meantime, if you're looking for an entry point to the API, [`P11.load_driver`](https://cryptosense.github.io/pkcs11/doc/P11.html#VALload_driver) will return a packed module of signature [`P11.S`](https://cryptosense.github.io/pkcs11/doc/P11.S.html).

**Comment by hannesm** [comment]
@emillon thx. Sample app would be appreciated :)

**Comment by hannesm** [comment]
@emillon did you had a chance to look into that?  would be nice if I could play a bit with it.

**Comment by emillon** [comment]
Thanks for the ping - that's still on my radar, I know what I'll include but didn't do it yet :)

In the meantime there's a code sample in #10 that you can play with (the setup code, upto `login`, is common to all such PKCS11 apps). It generates a key and encrypts a fixed plaintext using unpadded AES ECB.
