### ISSUE TITLE
Fix FreeBSD build

### ISSUE THREAD

**Issue by hannesm** [cryptosense/pkcs11#36]
I tried to compile and run the example application on my FreeBSD system (5baa80c adds `include <dlfcn.h>`).

Compilation and tests run fine afterwards, but the example application does not work - since `dlopen` on FreeBSD does not support the `RTLD_DEEPBIND` flag.  Once I remove this from `pkcs11.ml` (otherwise I get an assertion failure in `src/ctypes-foreign-base/dl_stubs.c` on line 66), I run into trouble: `Fatal error: exception Dl.DL_error("Undefined symbol \"C_Initialize\"")`.

Any idea how to solve this issue?  The shared object `dllpkcs11_rev_dllmain.so` provides the symbol `C_initialize`, but I don't know how to load that shared object -- if I add another call to `dlopen` in `load_driver` with this shared object, I get a `Undefined symbol "caml_startup"`.

Anyone with sufficient `dlopen` magic in their head who can suggest a workaround/fix for this? (//cc @yallop since he might be the one)

**Comment by emillon** [comment]
Hi,

There are a couple points I'd like to clarify.

There are two main use cases for this library:
- use a PKCS11 DLL to perform cryptographic operations on designated hardware or in a software token. (forward bindings)
- generate a DLL that conforms to the PKCS11 API, but implemented in OCaml. (reverse bindings)

The PKCS11 API has about 20 functions prefixed with `C_` - `C_Initialize` is one of them. Another way to access those functions is through `C_GetFunctionList`, which returns a structure with function pointers to each one.

The example is for forward bindings - by specifying `~use_get_function_list:Auto` it will try to detect if `C_GetFunctionList` works, use that, and fall back to calling functions directly otherwise.

I'm not sure what causes the `dlopen` error here - are you sure that you are passing a PKCS11 DLL? `objdump -T $DLL|grep C_` should find some defined symbols, at least `C_GetFunctionList`. Where does the exception come from? `load_driver` or `S.initialize`?

There is indeed a `C_Initialize` defined in `dllpkcs11_rev_dllmain.so`, but that is only used for reverse bindings. It exposes the PKCS11 API and will proxy calls to the actual functions defined in OCaml (that's also why it depends on the runtime). You don't need this here.

About `RTLD_DEEPBIND`: I think that it's only necessary for a specific use case which we happen to have: define a DLL that uses forward and reverse bindings at the same time. In that case, removing it shouldn't harm.

**Comment by hannesm** [comment]
@emillon thanks for your explanation.  turns out I tried to use `/usr/local/lib/libopensc.so.4.0.0`, but should have used `/usr/local/lib/opensc-pkcs11.so` instead.  Closing this issue, I'll followup with a minimal invasive patchset to get this working on FreeBSD.

**Comment by emillon** [comment]
Great, thanks in advance for the patches!
